Task1
vitaliysev/course_go_2024 pull request #1
Opened 2024-09-25 19:23 UTC by vitaliysev

2024-09-28 13:24 UTC, vmarunin requested changes
Я бы заменил 
```go
fmt.Println("Book not found")
```
на вывод какой тест не прошёл, чтобы было понятно. И ещё сделал бы exit с ненулевым кодом. 

Совсем же не понятно это успех или фейл. И если фейл, то в каком месте?

2024-09-28 13:24 UTC, vmarunin commented on task1/go.mod
> +go 1.18
Что же оно такое старое то? Это не обязательно исправлять, но лучше обновить компилятор, там много вкусного появилось.

2024-09-28 13:24 UTC, vmarunin commented on task1/library/library.go
> +func (library *MyLibrary) ChangeIdGenerator(NewMakeId IdGenerator) {
Переменные принято с маленькой буквы называть. Даже параметры функции

2024-09-28 13:24 UTC, vmarunin commented on task1/library/library.go
> +		for ; used[i]; i = rand.Intn(256) {
Константа в коде. 
Надо вынести хотя бы в константы в начало файла. И имя придумать говорящее

2024-09-28 13:24 UTC, vmarunin commented on task1/library/library.go
> +func NewLibrary(MakeId IdGenerator, storage Searcher) *MyLibrary {
makeId (а ещё лучше makeID)

2024-10-01 13:39 UTC, vmarunin requested changes
Надо разбить помельче по пакетам/файлам. Как минимум библиотека и оба стораджа кандидаты на отдельные пакеты

2024-10-01 13:58 UTC, vmarunin requested changes
В Go принят CamelCase, а не snake_case
Надо поменять идентификаторы

2024-10-01 15:10 UTC, vmarunin approved these changes
Принял

2024-10-01 15:16 UTC, vitaliysev commented
Мне самому мерджить?

2024-10-01 16:16 UTC, vmarunin commented
> Мне самому мерджить?

Подожди с этим до завтра, я пока сам не разобрался как тут принято по протоколу
На работе бывает по-разному, но чаще мерджит тот кому это надо. И разбирается с конфликтами если что. 

Тут конфликтов не будет, но порядок есть порядок

2024-10-02 06:11 UTC, vitaliysev commented
Окей, спасибо за информацию

2024-10-02 15:24 UTC, merged